### ISSUE TITLE
Add indifferent Hash access

### ISSUE THREAD

**Issue by dogweather** [dogweather/digbang#1]
When in Rails:

I.e., to further reduce visual noise, allow symbols as keys even if the Hash was created with String keys. It would make this gem more of a specialized thing rather than a just-do-one thing. But its application is for expressive code and syntactic sugar. And its slightly easier to read this:

```ruby
json_struct.dig!(:tree, :chapters, :sections)
```

Than this:

```ruby
json_struct.dig!("tree", "chapters", "sections")
```

Also, editors treat symbols differently from Strings in code highlighting (just like GitHub-flavored markdown does above), which would be handy.

**Comment by Skipants** [comment]
Hey, love the gem -- it's very useful.

I'm of the opinion that this is out of scope and it should be up to the underlying data structure to worry about this. In general that would be `Hash` vs. `ActiveSupport::HashWithIndifferentAccess`.

Even though it's an unusual case, Ruby's `Hash` does treat symbols and hashes with equal words as different keys. Consider:

```ruby
2.4.4 :001 > test = { key: "Hello", "key" => "World" }
 => {:key=>"Hello", "key"=>"World"}
2.4.4 :002 > test[:key]
 => "Hello"
2.4.4 :003 > test["key"]
 => "World"
```

**Comment by dogweather** [comment]
Thanks! And I've been thinking about this exact point: the underlying hash can be created as `HashWithIndifferentAccess` if needed. Glad you like the library.
